package helloWorld.HelloWorldWorkflow;

import com.amazonaws.services.simpleworkflow.flow.core.Promise;

public class GreeterWorkflowImpl implements GreeterWorkflow {
	
	/*
	 * this activity client class GreeterActivitiesClientImpl 
	 * is generated by using annotation processor on GreeterActivities
	 *  It creates the class names by simply appending "Client" and "ClientImpl" to the interface name.
	 * */
	
	/*
	 * the procxy wraps acitivity work implementations with SWF features 
	 * they can be find in .apt_generated folder 
	 * */
   private GreeterActivitiesClient operations = new GreeterActivitiesClientImpl();

   public void greet() {
	   
	   /*
	    * When the activities client method returns, the Promise<T> object is initially in an unready state, 
	    * which indicates that the object does not yet represent a valid return value.
        * When the corresponding activity method completes its task and returns, the framework assigns the return 
        * value to the Promise<T> object and puts it in the ready state.
	    * */
	   
     Promise<String> name = operations.getName();
     Promise<String> greeting = operations.getGreeting(name);
     operations.say(greeting);
   }
}